import Link from "next/link";
import { notFound, redirect } from "next/navigation";
import { revalidatePath } from "next/cache";
import { cancelMintJob, getMintJob } from "@/lib/server/mint-job-service";
import { getCurrentSession, requireCurrentUser } from "@/lib/server/session";

async function cancel(formData:FormData){"use server";const id=formData.get("jobId");if(typeof id!=="string")return;const user=await requireCurrentUser();await cancelMintJob(user.id,id);revalidatePath(`/dashboard/jobs/${id}`);revalidatePath("/dashboard/jobs");}
export default async function JobPage({params}:{params:Promise<{id:string}>}){const session=await getCurrentSession();if(!session?.user)redirect("/");const {id}=await params;const result=await getMintJob(session.user.id,id);if(!result)notFound();const {job,history}=result;return <main className="min-h-screen bg-neutral-950 text-white"><div className="mx-auto max-w-3xl px-5 py-8"><Link href="/dashboard/jobs" className="text-sm text-neutral-500 hover:text-white">← Mint jobs</Link><div className="mt-8 flex flex-wrap items-center gap-3"><h1 className="text-3xl font-semibold">Mint job</h1><span className="rounded-full bg-white/5 px-2.5 py-1 text-xs font-semibold text-neutral-300">{job.state}</span></div><div className="mt-8 grid gap-px overflow-hidden rounded-2xl border border-white/10 bg-white/10 sm:grid-cols-2"><Info label="Network" value={job.chainId===8453?"Base":"Base Sepolia"}/><Info label="Scheduled" value={job.scheduledFor.toLocaleString()}/><Info label="Contract" value={job.contractAddress} mono/><Info label="Value (wei)" value={job.valueWei} mono/></div><section className="mt-6 rounded-2xl border border-white/10 bg-white/[.03] p-5"><h2 className="font-semibold">Transaction history</h2>{history.length===0?<p className="mt-3 text-sm text-neutral-500">No signed transaction yet.</p>:<div className="mt-4 space-y-3">{history.map((tx,i)=><div key={`${tx.hash}-${i}`} className="rounded-lg border border-white/10 p-3"><p className="text-xs font-medium text-neutral-400">{tx.state}</p><p className="mt-1 break-all font-mono text-xs text-neutral-300">{tx.hash}</p></div>)}</div>}</section>{job.state==="SCHEDULED"?<form action={cancel} className="mt-6"><input type="hidden" name="jobId" value={job.id}/><button className="rounded-lg border border-red-400/30 px-4 py-2.5 text-sm font-semibold text-red-300 hover:bg-red-400/10">Cancel scheduled mint</button><p className="mt-2 text-xs text-neutral-600">Cancellation is unavailable after the worker claims the job.</p></form>:null}</div></main>}
function Info({label,value,mono=false}:{label:string;value:string;mono?:boolean}){return <div className="bg-neutral-950 p-5"><p className="text-xs uppercase tracking-wider text-neutral-600">{label}</p><p className={`mt-2 break-all text-sm text-neutral-300 ${mono?"font-mono":""}`}>{value}</p></div>}
