import { networkName } from "@/lib/networks";
import Link from "next/link";
import { redirect } from "next/navigation";
import { listMintJobs } from "@/lib/server/mint-job-service";
import { getCurrentSession } from "@/lib/server/session";

export default async function JobsPage(){const session=await getCurrentSession();if(!session?.user)redirect("/");const rows=await listMintJobs(session.user.id);const jobs=rows.slice(0,5);return <main className="min-h-screen bg-neutral-950 text-white"><div className="mx-auto max-w-4xl px-5 py-8"><Link href="/dashboard" className="text-sm text-neutral-500 hover:text-white">← Dashboard</Link><p className="mt-8 text-xs font-semibold uppercase tracking-[.2em] text-emerald-400">Mint activity</p><h1 className="mt-2 text-3xl font-semibold">Mint jobs</h1><Link href="/dashboard/jobs/new" className="mt-4 inline-block rounded bg-emerald-700 px-4 py-2">New mint</Link><p className="mt-2 text-sm text-neutral-400">Create a mint here or through your linked Telegram account.</p>{jobs.length===0?<div className="mt-8 rounded-2xl border border-dashed border-white/15 p-10 text-center"><h2 className="font-semibold">No mint jobs yet</h2><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-neutral-500">Connect Telegram and start a mint with the bot. It will appear here as soon as it is scheduled.</p><Link href="/dashboard/telegram" className="mt-5 inline-block text-sm font-medium text-emerald-400">Open Telegram setup →</Link></div>:<div className="mt-8 space-y-3">{jobs.map(job=><Link key={job.id} href={`/dashboard/jobs/${job.id}`} className="grid gap-4 rounded-xl border border-white/10 bg-white/[.03] p-5 transition hover:border-white/25 sm:grid-cols-[1fr_auto] sm:items-center"><div><div className="flex flex-wrap items-center gap-2"><span className="font-mono text-sm">{short(job.contractAddress)}</span><State state={job.state}/></div><p className="mt-2 text-xs text-neutral-500">{networkName(job.chainId)} · scheduled {job.scheduledFor.toLocaleString()}</p></div><span className="text-sm text-emerald-400">Details →</span></Link>)}</div>}</div></main>}
function short(v:string){return `${v.slice(0,8)}…${v.slice(-6)}`}
function State({state}:{state:string}){const done=state==="SUCCEEDED";const bad=state==="FAILED"||state==="CANCELLED";return <span className={`rounded-full px-2 py-1 text-[11px] font-semibold ${done?"bg-emerald-400/10 text-emerald-300":bad?"bg-red-400/10 text-red-300":"bg-blue-400/10 text-blue-300"}`}>{state}</span>}
